sudo: false

language: java


# https://github.com/travis-ci/travis-ci/issues/3259#issuecomment-130860338
addons:
  apt:
    packages:
      - oracle-java8-installer

install: mvn -B install -U -DskipTests=true

after_success:
  - util/deploy_snapshot.sh
  - util/update_snapshot_docs.sh

cache:
  directories:
  - $HOME/.m2

jdk:  oraclejdk8

env:
  - RUN="travis_wait 360 mvn -B verify -U -Dmaven.javadoc.skip=true -Dgwt.test.include=**/DoesNotMatchAnyTests.java"
  - RUN='.fix/runClient.sh https://github.com/cucumber/cucumber-jvm.git com.google.guava'
  - RUN='.fix/runClient.sh https://github.com/alibaba/canal.git com.google.guava'
  - RUN='.fix/runClient.sh https://github.com/dropwizard/dropwizard.git com.google.guava'



# https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
script: eval ${RUN}


branches:
  only:
    - master
    - /^release.*$/
